/* Common Playwright mistakes — synthesized from official best practices + community guides */
window.MISTAKES_DATA = {
  hub: {
    title: "Anti-patterns & common mistakes",
    lead: "Frameworks don’t erase bad habits. These patterns show up across nearly every flaky suite: sleeps, brittle selectors, shared data, weak asserts, force-clicks, and CI blind spots. Learn the wrong instinct, the real cause, and the Playwright-native fix.",
  },

  sourcesNote: "Synthesized from Playwright best practices, TestDino / QABash / Elaichenkov mistake guides, Better Stack flake guides, and related community articles — rewritten for this offline study site.",

  glance: [
    { m: "waitForTimeout()", i: "Slow + random CI failures" },
    { m: "One-shot isVisible / textContent", i: "Timing luck, no retry" },
    { m: "Fragile CSS / XPath", i: "Breaks on every redesign" },
    { m: "Missing await", i: "Race with next line" },
    { m: "Shared accounts / serial chains", i: "Fails only under workers" },
    { m: "{ force: true }", i: "Hides real overlays" },
    { m: "networkidle as “ready”", i: "Too early or never" },
    { m: "UI login every test", i: "Slow + flaky setup" },
    { m: "No traces in CI", i: "Guessing in the dark" },
    { m: "Retries as the fix", i: "Masks root cause" },
  ],

  pitfalls: [
    {
      id: "m-sleep",
      title: "Hard sleeps: waitForTimeout()",
      think: "The UI needs a moment — sleep 3 seconds and move on.",
      actual: "Too short on slow CI, too long on fast machines. Sleeps don’t check readiness; they hope.",
      fix: "Use web-first expect(...).toBeVisible() / waitForResponse / waitForURL. Never ship sleeps in production suites.",
      bad: `await page.getByRole('button', { name: 'Load' }).click();\nawait page.waitForTimeout(3000);\nawait expect(page.getByTestId('chart')).toBeVisible();`,
      good: `await page.getByRole('button', { name: 'Load' }).click();\nawait expect(page.getByTestId('chart')).toBeVisible();`,
    },
    {
      id: "m-oneshot",
      title: "One-shot checks instead of web-first assertions",
      think: "expect(await loc.isVisible()).toBe(true) is fine — it’s still an assertion.",
      actual: "Boolean snapshot has no retry. The element may appear 50ms later → flake.",
      fix: "await expect(locator).toBeVisible() / toHaveText() / toHaveURL() — Playwright retries until timeout.",
      bad: `expect(await page.getByTestId('status').isVisible()).toBeTruthy();\nexpect(await page.getByTestId('name').textContent()).toBe('Alice');`,
      good: `await expect(page.getByTestId('status')).toBeVisible();\nawait expect(page.getByTestId('name')).toHaveText('Alice');`,
    },
    {
      id: "m-noassert",
      title: "Tests with no assertions",
      think: "If goto and click don’t throw, the feature works.",
      actual: "That’s a script, not a test. False greens ship broken UI.",
      fix: "Always assert a user-visible outcome (heading, URL, toast, table row).",
      bad: `test('opens dashboard', async ({ page }) => {\n  await page.goto('/dashboard');\n});`,
      good: `test('opens dashboard', async ({ page }) => {\n  await page.goto('/dashboard');\n  await expect(page.getByRole('heading', { name: 'Dashboard' })).toBeVisible();\n});`,
    },
    {
      id: "m-await",
      title: "Missing await on Playwright calls",
      think: "Click is fire-and-forget; the next line will be fine.",
      actual: "Every Playwright API is async. Missing await races the next action against an unfinished one.",
      fix: "Await every call. Enable @typescript-eslint/no-floating-promises.",
      bad: `page.getByRole('button', { name: 'Sign in' }).click(); // missing await\nawait expect(page.getByRole('heading', { name: 'Dashboard' })).toBeVisible();`,
      good: `await page.getByRole('button', { name: 'Sign in' }).click();\nawait expect(page.getByRole('heading', { name: 'Dashboard' })).toBeVisible();`,
    },
    {
      id: "m-selectors",
      title: "Fragile CSS / absolute XPath",
      think: "DevTools copy of .btn-primary-v2 /html/body/div[3]/… is precise.",
      actual: "Classes and wrapper divs change constantly. Suites become redesign tax.",
      fix: "Prefer getByRole / getByLabel / getByTestId. XPath only for legacy/complex axes — short and relative.",
      bad: `await page.locator('div > div > .content-wrapper .btn-next').click();`,
      good: `await page.getByRole('button', { name: 'Next' }).click();`,
    },
    {
      id: "m-prewait",
      title: "waitFor before actions that already auto-wait",
      think: "I must waitFor({ state: 'visible' }) before every click.",
      actual: "click/fill already wait for actionability. Extra waits add noise, not safety.",
      fix: "Just click/fill. Assert outcomes with web-first expect.",
      bad: `await page.getByRole('button', { name: 'Submit' }).waitFor({ state: 'visible' });\nawait page.getByRole('button', { name: 'Submit' }).click();`,
      good: `await page.getByRole('button', { name: 'Submit' }).click();`,
    },
    {
      id: "m-force",
      title: "Overusing { force: true }",
      think: "Click is intercepted — force it through.",
      actual: "Force skips actionability and hides overlays/disabled states users also can’t click.",
      fix: "Close the modal/spinner first. Force only for rare intentional bypasses.",
      bad: `await page.getByRole('button', { name: 'Delete' }).click({ force: true });`,
      good: `await expect(page.getByTestId('loading-overlay')).toBeHidden();\nawait page.getByRole('button', { name: 'Delete' }).click();`,
    },
    {
      id: "m-networkidle",
      title: "Relying on networkidle as “page ready”",
      think: "waitUntil: 'networkidle' means the SPA finished loading.",
      actual: "Long-polling/WebSockets never idle; other apps idle before critical XHR finishes.",
      fix: "Assert a user-visible ready signal (heading, skeleton gone, key data).",
      bad: `await page.goto('/app', { waitUntil: 'networkidle' });`,
      good: `await page.goto('/app');\nawait expect(page.getByRole('heading', { name: 'Dashboard' })).toBeVisible();`,
    },
    {
      id: "m-response-order",
      title: "Wrong waitForResponse ordering",
      think: "Click first, then wait for the API — or await the waiter before registering.",
      actual: "If you await the waiter before the click, you block forever. If you click then wait, you can miss a fast response.",
      fix: "1) Create promise (no await) 2) trigger action 3) await promise.",
      bad: `await page.getByRole('button', { name: 'Load' }).click();\nawait page.waitForResponse(r => r.url().includes('/api/data'));`,
      good: `const resP = page.waitForResponse(r => r.url().includes('/api/data') && r.ok());\nawait page.getByRole('button', { name: 'Load' }).click();\nawait resP;`,
    },
    {
      id: "m-retry-loop",
      title: "Hand-rolled retry loops",
      think: "While retries-- with sleep until text matches.",
      actual: "Reimplements timeouts poorly; hard to debug; fights Playwright’s model.",
      fix: "Use expect(...).toPass() or expect.poll() with short inner timeouts.",
      bad: `let n = 5;\nwhile (n--) {\n  if ((await page.getByTestId('total').textContent()) === '100') break;\n  await page.waitForTimeout(1000);\n}`,
      good: `await expect.poll(async () => {\n  return parseInt(await page.getByTestId('total').textContent() || '0', 10);\n}).toBe(100);`,
    },
    {
      id: "m-isolation",
      title: "Shared state / order-dependent tests",
      think: "Test B can reuse what Test A created — saves setup time.",
      actual: "Parallel workers collide; serial chains skip remaining tests when one fails.",
      fix: "Fresh context per test (default). Unique faker data. Prefer one multi-step test with test.step over describe.serial.",
      bad: `test.describe.serial('checkout', () => {\n  test('add to cart', async ({ page }) => { /* leaves cart */ });\n  test('pay', async ({ page }) => { /* needs previous cart */ });\n});`,
      good: `test('checkout flow', async ({ page }) => {\n  await test.step('add to cart', async () => { /* ... */ });\n  await test.step('pay', async () => { /* ... */ });\n});`,
    },
    {
      id: "m-ui-setup",
      title: "Doing all setup through the UI",
      think: "Every test should login and seed data like a real user.",
      actual: "Slow, flaky, and re-tests login 500 times instead of the feature under test.",
      fix: "API/DB seed + storageState for auth. UI only for the behaviour under test.",
      bad: `// every test: goto login → fill → click → navigate 5 screens → finally assert`,
      good: `// project setup writes storageState; test uses authenticated context\n// request.post('/api/orders', { data }) then page.goto('/orders')`,
    },
    {
      id: "m-weak-assert",
      title: "Weak assertions (exists ≠ works)",
      think: "toBeAttached / count > 0 proves the feature.",
      actual: "Wrong data can still “exist.” False confidence.",
      fix: "Assert business outcomes: correct text, totals, URL, saved record visible.",
      bad: `await expect(page.getByTestId('order-row')).toBeAttached();`,
      good: `await expect(page.getByTestId('order-total')).toHaveText('₹1,299');\nawait expect(page).toHaveURL(/\\/orders\\/\\d+/);`,
    },
    {
      id: "m-exact",
      title: "Substring locators without exact: true",
      think: "getByText('Submit') clearly means the Submit button.",
      actual: "Also matches “Submit Order” / “Submitting…”. Strict mode or wrong click.",
      fix: "Use { exact: true } or a more specific role+name.",
      bad: `await page.getByText('Submit').click();`,
      good: `await page.getByRole('button', { name: 'Submit', exact: true }).click();`,
    },
    {
      id: "m-deprecated",
      title: "Deprecated waits (waitForNavigation / waitForSelector habits)",
      think: "Promise.all([waitForNavigation(), click()]) is the classic pattern.",
      actual: "Deprecated APIs miss SPA navigations and encourage outdated mental models.",
      fix: "Prefer waitForURL, web-first expect, and locator auto-wait.",
      bad: `await Promise.all([\n  page.waitForNavigation(),\n  page.getByRole('link', { name: 'Profile' }).click(),\n]);`,
      good: `await page.getByRole('link', { name: 'Profile' }).click();\nawait page.waitForURL('**/profile');`,
    },
    {
      id: "m-trace",
      title: "Skipping traces / debugging blind in CI",
      think: "Screenshot is enough; re-run the pipeline until it fails again.",
      actual: "You lose DOM/network/timeline evidence. Hours wasted.",
      fix: "trace: 'on-first-retry' (or retain-on-failure). Open HTML report → Trace Viewer.",
      bad: `// use: { screenshot: 'off', trace: 'off' } in CI`,
      good: `// use: { trace: 'on-first-retry', screenshot: 'only-on-failure', video: 'retain-on-failure' }`,
    },
    {
      id: "m-retries",
      title: "Retries as the “fix” for flakes",
      think: "retries: 5 will keep CI green.",
      actual: "Masks bugs. Real failures look like “eventually passed.”",
      fix: "Use 1–2 CI retries as a safety net. Fix with --repeat-each + traces. Quarantine with owner+expiry.",
      bad: `retries: 5, // hope is not a strategy`,
      good: `retries: process.env.CI ? 2 : 0,\n// then fix flakes; track flake rate`,
    },
    {
      id: "m-thirdparty",
      title: "Automating third-party UIs you don’t control",
      think: "We must click through real Google OAuth / Stripe hosted UI every time.",
      actual: "Bot detection, rate limits, and UI churn break your suite — not your product.",
      fix: "Mock IdP/payment callbacks for most tests; keep a tiny real smoke suite if needed.",
      bad: `// every test opens Google consent screen in CI`,
      good: `await page.route('**/oauth/callback**', route => route.fulfill({ /* crafted token */ }));`,
    },
    {
      id: "m-pom-fat",
      title: "Monolithic Page Objects / returning pages from every action",
      think: "One LoginPage with 80 methods and login() returning DashboardPage is “proper POM.”",
      actual: "Tight coupling and mega-classes; every navigation change ripples widely.",
      fix: "Small page/component objects. Specs compose them. Prefer void actions unless chaining truly helps.",
      bad: `async login(...): Promise<DashboardPage> {\n  /* fill+click */\n  return new DashboardPage(this.page);\n}`,
      good: `async login(...): Promise<void> {\n  /* fill+click */\n}\n// test creates DashboardPage when it needs it`,
    },
    {
      id: "m-eslint",
      title: "No Playwright ESLint / typecheck in CI",
      think: "We’ll catch bad patterns in code review.",
      actual: "Floating promises, waitForTimeout, and force:true keep landing.",
      fix: "eslint-plugin-playwright + tsc --noEmit on CI.",
      bad: `// no lint rules for tests/`,
      good: `// eslint-plugin-playwright flat/recommended on tests/**\n// "typecheck": "tsc --noEmit"`,
    },
  ],

  interview: [
    {
      q: "Why is waitForTimeout considered harmful in Playwright?",
      a: "It waits for time, not readiness. Too short → flake; too long → slow suites. Prefer web-first assertions or waits tied to URL/response/UI state.",
    },
    {
      q: "What’s wrong with expect(await locator.isVisible()).toBe(true)?",
      a: "One-shot boolean — no retry. Use await expect(locator).toBeVisible() so Playwright polls until timeout.",
    },
    {
      q: "How do you correctly wait for an API that a click triggers?",
      a: "const p = page.waitForResponse(...); await click(); await p; — register first, act second, await third.",
    },
    {
      q: "When is { force: true } acceptable?",
      a: "Rarely — only when you intentionally bypass actionability and accept that users couldn’t click either. Prefer dismissing overlays.",
    },
    {
      q: "How do you keep tests isolated under parallel workers?",
      a: "Default fresh BrowserContext per test; unique data; no shared mutable accounts; avoid describe.serial unless truly required.",
    },
    {
      q: "networkidle failed locally but worked once — what’s going on?",
      a: "Idle is brittle with websockets/analytics. Assert a visible ready state instead of network silence.",
    },
    {
      q: "Retries: 2 in CI — good or bad?",
      a: "Good as a safety net for infra blips; bad as the only flake strategy. Still reproduce with --repeat-each and fix root cause.",
    },
    {
      q: "What artefacts should CI keep for failures?",
      a: "trace on-first-retry, screenshot/video on failure, HTML report uploaded as artifact. Trace Viewer beats guessing from logs.",
    },
    {
      q: "How do you speed up a suite without deleting coverage?",
      a: "API seed instead of UI setup, storageState auth, parallel workers + sharding, mock third parties, keep E2E for critical paths.",
    },
    {
      q: "Substring getByText('Save') started matching two nodes — fix?",
      a: "exact: true, or getByRole('button', { name: 'Save', exact: true }), or scope under a unique parent.",
    },
    {
      q: "Why prefer positive toBeHidden over not.toBeVisible?",
      a: "Clearer intent and better failure messages; positive matchers are easier to read in reviews.",
    },
    {
      q: "Interview one-liner for flake triage?",
      a: "Reproduce with --repeat-each and retries=0, open the trace, categorize (wait/locator/state/env), fix the class of bug, then prove stability.",
    },
  ],
};
