/* Generated by tools/generate-sw.mjs — do not hand-edit. Run: npm run generate:sw */
const CACHE = 'pw-learn-836f39ea8946';
const ASSETS = [
  "./",
  "./404.html",
  "./app.js",
  "./assessments-data.js",
  "./bank-demo.js",
  "./cases-data.js",
  "./drill-data.js",
  "./framework-academy.js",
  "./framework-data.js",
  "./framework-diagrams.js",
  "./fsrs-app.js",
  "./gamification.js",
  "./gap-pages-data.js",
  "./gap-practice-data.js",
  "./gap-practice.js",
  "./hub-widgets.js",
  "./icons/icon-192.png",
  "./icons/icon-512.png",
  "./icons/icon-maskable-512.png",
  "./index.html",
  "./interview-data.js",
  "./interview-essentials-data.js",
  "./interviewer-data.js",
  "./interviewer-diagrams.js",
  "./interviewer-mode.js",
  "./manifest.webmanifest",
  "./miniapps-data.js",
  "./mistakes-data.js",
  "./mock-exam-pool.js",
  "./mock-exam.js",
  "./personal-knowledge.js",
  "./playground-data.js",
  "./practice-widgets.js",
  "./quiz-data.js",
  "./readiness-engine.js",
  "./readiness-ui.js",
  "./reading-times.js",
  "./safe-html.js",
  "./search-index.js",
  "./section-mcq-data.js",
  "./skills-data.js",
  "./skills-modules.js",
  "./skills-practice-data.js",
  "./skills-practice-widgets.js",
  "./storage.js",
  "./stuck-data.js",
  "./study-planner.js",
  "./styles.css",
  "./sw.js",
  "./topics-data.js",
  "./ui-2026.js",
  "./vendor/minisearch.js",
  "./vendor/ts-fsrs.js",
  "./xpath-data.js",
  "./xpath-widgets.js"
];

const NAV = ['navigate', 'reload'];

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE).then((c) => c.addAll(ASSETS)).then(() => self.skipWaiting()),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))),
    ).then(() => self.clients.claim()),
  );
});

function isHtml(request) {
  return NAV.includes(request.mode) || request.headers.get('accept')?.includes('text/html');
}

async function networkFirst(request) {
  try {
    const res = await fetch(request);
    if (res.ok) {
      const copy = res.clone();
      caches.open(CACHE).then((c) => c.put(request, copy));
    }
    return res;
  } catch {
    const cached = await caches.match(request);
    if (cached) return cached;
    return caches.match('./404.html');
  }
}

async function staleWhileRevalidate(request) {
  const cached = await caches.match(request);
  const fetchPromise = fetch(request)
    .then((res) => {
      if (res.ok && res.type === 'basic') {
        const copy = res.clone();
        caches.open(CACHE).then((c) => c.put(request, copy));
      }
      return res;
    })
    .catch(() => null);
  return cached || fetchPromise || caches.match('./index.html');
}

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;
  if (isHtml(req)) {
    event.respondWith(networkFirst(req));
    return;
  }
  event.respondWith(staleWhileRevalidate(req));
});

self.addEventListener('message', (event) => {
  if (event.data?.type === 'SKIP_WAITING') self.skipWaiting();
});
