/* Generated by tools/content/build-content.mjs — do not edit by hand.
 * SSOT: interview-qa/_meta/topics.json
 */
window.TOPICS_REGISTRY = {
  version: 1,
  description: "Canonical topic registry for Skill Modules and cross-track references.",
  topics: [
    {
      key: "api-rest-basics",
      displayName: "REST fundamentals",
      track: "SK-API",
    },
    {
      key: "api-http-methods",
      displayName: "HTTP methods & idempotency",
      track: "SK-API",
    },
    {
      key: "api-status-codes",
      displayName: "Status codes in automation",
      track: "SK-API",
    },
    {
      key: "api-request-fixture",
      displayName: "Playwright request fixture",
      track: "SK-API",
    },
    {
      key: "api-json-assertions",
      displayName: "JSON parsing & assertions",
      track: "SK-API",
    },
    {
      key: "api-auth-headers",
      displayName: "Auth headers & tokens",
      track: "SK-API",
    },
    {
      key: "api-setup-teardown",
      displayName: "API setup before UI tests",
      track: "SK-API",
    },
    {
      key: "api-hybrid-ui",
      displayName: "Hybrid API + UI flows",
      track: "SK-API",
    },
    {
      key: "api-pagination",
      displayName: "Pagination & query params",
      track: "SK-API",
    },
    {
      key: "api-negative-testing",
      displayName: "Negative API testing",
      track: "SK-API",
    },
    {
      key: "api-graphql",
      displayName: "GraphQL with Playwright",
      track: "SK-API",
    },
    {
      key: "api-client-fixture",
      displayName: "Reusable API client fixtures",
      track: "SK-API",
    },
    {
      key: "ts-basics",
      displayName: "TypeScript essentials",
      track: "SK-TS",
    },
    {
      key: "ts-strict",
      displayName: "Strict mode & compiler options",
      track: "SK-TS",
    },
    {
      key: "ts-async-await",
      displayName: "Async/await in tests",
      track: "SK-TS",
    },
    {
      key: "ts-interfaces",
      displayName: "Interfaces for test models",
      track: "SK-TS",
    },
    {
      key: "ts-factories",
      displayName: "Type-safe test data factories",
      track: "SK-TS",
    },
    {
      key: "ts-generics",
      displayName: "Generics in fixtures",
      track: "SK-TS",
    },
    {
      key: "ts-unions",
      displayName: "Union & discriminated types",
      track: "SK-TS",
    },
    {
      key: "ts-utility-types",
      displayName: "Utility types (Partial, Pick)",
      track: "SK-TS",
    },
    {
      key: "ts-modules",
      displayName: "Modules & barrel exports",
      track: "SK-TS",
    },
    {
      key: "ts-type-guards",
      displayName: "Type guards & narrowing",
      track: "SK-TS",
    },
    {
      key: "sql-select",
      displayName: "SELECT & filtering",
      track: "SK-SQL",
    },
    {
      key: "sql-joins",
      displayName: "JOINs for verification",
      track: "SK-SQL",
    },
    {
      key: "sql-aggregates",
      displayName: "Aggregates & GROUP BY",
      track: "SK-SQL",
    },
    {
      key: "sql-subqueries",
      displayName: "Subqueries & EXISTS",
      track: "SK-SQL",
    },
    {
      key: "sql-dml",
      displayName: "INSERT/UPDATE/DELETE seeding",
      track: "SK-SQL",
    },
    {
      key: "sql-transactions",
      displayName: "Transactions & rollback",
      track: "SK-SQL",
    },
    {
      key: "sql-indexes",
      displayName: "Indexes & EXPLAIN",
      track: "SK-SQL",
    },
    {
      key: "sql-constraints",
      displayName: "Constraints validation",
      track: "SK-SQL",
    },
    {
      key: "git-workflow",
      displayName: "Git workflow for QA",
      track: "SK-GIT",
    },
    {
      key: "git-branching",
      displayName: "Branching strategies",
      track: "SK-GIT",
    },
    {
      key: "git-merge-rebase",
      displayName: "Merge vs rebase",
      track: "SK-GIT",
    },
    {
      key: "git-conflicts",
      displayName: "Conflict resolution",
      track: "SK-GIT",
    },
    {
      key: "git-bisect",
      displayName: "git bisect for flakes",
      track: "SK-GIT",
    },
    {
      key: "git-ci",
      displayName: "CI triggers & protected branches",
      track: "SK-GIT",
    },
    {
      key: "http-anatomy",
      displayName: "HTTP request/response anatomy",
      track: "SK-HTTP",
    },
    {
      key: "http-headers-cookies",
      displayName: "Headers, cookies & sessions",
      track: "SK-HTTP",
    },
    {
      key: "http-content-type",
      displayName: "Content types & MIME",
      track: "SK-HTTP",
    },
    {
      key: "http-cors",
      displayName: "CORS & preflight",
      track: "SK-HTTP",
    },
    {
      key: "http-tls",
      displayName: "HTTPS & TLS basics",
      track: "SK-HTTP",
    },
    {
      key: "http-caching",
      displayName: "Caching & conditional requests",
      track: "SK-HTTP",
    },
    {
      key: "sec-owasp",
      displayName: "OWASP Top 10 awareness",
      track: "SK-SEC",
    },
    {
      key: "sec-xss",
      displayName: "XSS prevention verification",
      track: "SK-SEC",
    },
    {
      key: "sec-csrf",
      displayName: "CSRF token validation",
      track: "SK-SEC",
    },
    {
      key: "sec-session",
      displayName: "Session & cookie security",
      track: "SK-SEC",
    },
    {
      key: "sec-secrets",
      displayName: "Secrets in test environments",
      track: "SK-SEC",
    },
    {
      key: "fixtures",
      displayName: "Custom fixtures (test.extend)",
      track: "framework",
    },
    {
      key: "sharding",
      displayName: "CI sharding & merge reports",
      track: "framework",
    },
    {
      key: "network-mocking",
      displayName: "Network mocking (page.route)",
      track: "framework",
    },
    {
      key: "storage-state",
      displayName: "Storage state & auth setup",
      track: "framework",
    },
    {
      key: "mergeTests",
      displayName: "mergeTests composition",
      track: "framework",
    },
    {
      key: "page-objects",
      displayName: "Thin page object model",
      track: "framework",
    },
    {
      key: "locators",
      displayName: "Web-first locators",
      track: "framework",
    },
    {
      key: "trace-debugging",
      displayName: "Trace & debugging artifacts",
      track: "framework",
    },
    {
      key: "ci-gates",
      displayName: "CI quality gates",
      track: "framework",
    },
    {
      key: "auth-setup",
      displayName: "Auth setup projects",
      track: "framework",
    },
    {
      key: "test-isolation",
      displayName: "Test isolation patterns",
      track: "framework",
    },
    {
      key: "parallel-workers",
      displayName: "Worker scope & parallelism",
      track: "framework",
    },
    {
      key: "reporters",
      displayName: "Reporters & artifacts",
      track: "framework",
    },
    {
      key: "grep-tags",
      displayName: "Tags & grep filtering",
      track: "framework",
    },
    {
      key: "contract-testing",
      displayName: "Contract testing basics",
      track: "framework",
    }
  ],
};
