#!/usr/bin/env node
/** Generate learning-site/sw.js from index.html + app.js lazy bundles (author-time, zero-build runtime). */
import fs from 'node:fs';
import crypto from 'node:crypto';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const htmlPath = path.join(ROOT, 'learning-site/index.html');
const appPath = path.join(ROOT, 'learning-site/app.js');
const outPath = path.join(ROOT, 'learning-site/sw.js');

const html = fs.readFileSync(htmlPath, 'utf8');
const appJs = fs.readFileSync(appPath, 'utf8');
const assets = new Set(['./', './index.html', './404.html', './styles.css', './manifest.webmanifest']);

for (const m of html.matchAll(/<script[^>]+src="([^"]+)"/gi)) {
  if (!m[1].startsWith('http')) assets.add('./' + m[1].replace(/^\.\//, ''));
}
for (const m of html.matchAll(/<link[^>]+rel="stylesheet"[^>]+href="([^"]+)"/gi)) {
  if (!m[1].startsWith('http')) assets.add('./' + m[1].replace(/^\.\//, ''));
}

// All lazy bundles from SECTION_LAZY_SCRIPTS in app.js.
for (const m of appJs.matchAll(/['"]([^'"]+\.js)['"]/g)) {
  const f = m[1];
  if (f.startsWith('http') || f.includes('*')) continue;
  if (/\.js$/.test(f)) assets.add('./' + f.replace(/^\.\//, ''));
}

// PWA icons + search index (lazy but must offline-cache).
['search-index.js', 'icons/icon-192.png', 'icons/icon-512.png', 'icons/icon-maskable-512.png'].forEach(
  (f) => assets.add('./' + f),
);

const list = [...assets].sort();
const hash = crypto.createHash('sha256').update(list.join('\n')).digest('hex').slice(0, 12);
const CACHE = `pw-learn-${hash}`;

const body = `/* Generated by tools/generate-sw.mjs — do not hand-edit. Run: npm run generate:sw */
const CACHE = '${CACHE}';
const ASSETS = ${JSON.stringify(list, null, 2)};

const NAV = ['navigate', 'reload'];

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE).then((c) => c.addAll(ASSETS)).then(() => self.skipWaiting()),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))),
    ).then(() => self.clients.claim()),
  );
});

function isHtml(request) {
  return NAV.includes(request.mode) || request.headers.get('accept')?.includes('text/html');
}

async function networkFirst(request) {
  try {
    const res = await fetch(request);
    if (res.ok) {
      const copy = res.clone();
      caches.open(CACHE).then((c) => c.put(request, copy));
    }
    return res;
  } catch {
    const cached = await caches.match(request);
    if (cached) return cached;
    return caches.match('./404.html');
  }
}

async function staleWhileRevalidate(request) {
  const cached = await caches.match(request);
  const fetchPromise = fetch(request)
    .then((res) => {
      if (res.ok && res.type === 'basic') {
        const copy = res.clone();
        caches.open(CACHE).then((c) => c.put(request, copy));
      }
      return res;
    })
    .catch(() => null);
  return cached || fetchPromise || caches.match('./index.html');
}

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;
  if (isHtml(req)) {
    event.respondWith(networkFirst(req));
    return;
  }
  event.respondWith(staleWhileRevalidate(req));
});

self.addEventListener('message', (event) => {
  if (event.data?.type === 'SKIP_WAITING') self.skipWaiting();
});
`;

fs.writeFileSync(outPath, body);
console.log(`sw.js generated — ${list.length} assets, cache ${CACHE}`);
